services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./regional_history:/regional_history
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "uvicorn architecture_bot.wsgi:application --host 0.0.0.0 --port 8000"
    depends_on:
      - database

  database:
    image: postgres:14.10-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    build: nginx/.
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web-app
