services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./regional_history:/regional_history
    environment:
      - DB_HOST=database
      - DB_NAME=region_history
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.10-alpine
    environment:
      - POSTGRES_DB=region_history
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

