# Generated by Django 3.2.16 on 2023-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название места')),
                ('description', models.TextField(verbose_name='Описание места')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес места')),
                ('coordinate_x', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Координата места по оси X')),
                ('coordinate_y', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Координата места по оси Y')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото места')),
            ],
        ),
    ]
